apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner
  template:
    metadata:
      labels:
        app: miner
    spec:
      containers:
      - name: webui
        image: 127.0.0.1:30000/webui:v0.1
        ports:
          - name: http-port
            containerPort: 80
      - name: rng
        image: 127.0.0.1:30000/rng:v0.1
        ports:
          - name: http-port
            containerPort: 80
      - name: hasher
        image: 127.0.0.1:30000/hasher:v0.1
        ports:
          - name: http-port
            containerPort: 80
      - name: worker
        image: 127.0.0.1:30000/worker:v0.1
        ports:
          - name: http-port
            containerPort: 80
      - name: redis
        image: redis
        ports:
          - name: http-port
            containerPort: 6379
