apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: ${REGISTRY-127.0.0.1:5000}/webui:${TAG-latest}
        ports:
          - name: http-port
            containerPort: 80
            
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: ${REGISTRY-127.0.0.1:5000}/rng:${TAG-latest}
        ports:
          - name: http-port
            containerPort: 80
            
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: webui
        image: ${REGISTRY-127.0.0.1:5000}/hasher:${TAG-latest}
        ports:
          - name: http-port
            containerPort: 80
            
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: webui
        image: ${REGISTRY-127.0.0.1:5000}/worker:${TAG-latest}
        ports:
          - name: http-port
            containerPort: 80
            
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - name: http-port
            containerPort: 6379
